# Generated by Django 4.0.4 on 2022-05-05 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucherapp', '0002_rename_fixed_percentage_discount_specialoffer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercode',
            name='special_offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voucherapp.specialoffer'),
            preserve_default=False,
        ),
    ]
