# Generated by Django 4.0.4 on 2022-05-05 06:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucherapp', '0003_vouchercode_special_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='discount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vouchercode',
            name='code',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='vouchercode',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucherapp.customer'),
        ),
    ]
