# Generated by Django 4.0.4 on 2022-05-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucherapp', '0004_alter_specialoffer_discount_alter_vouchercode_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vouchercode',
            unique_together={('customer', 'special_offer')},
        ),
    ]
