# Generated by Django 4.0.4 on 2022-05-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialoffer',
            old_name='fixed_percentage_discount',
            new_name='discount',
        ),
    ]
